language: python

sudo: false

python:
  - 3.5.4
  - 3.6.3

services:
  - redis-server

install:
  - ci/install.sh

script:
  - python setup.py test --coverage -q
  - flake8
  - python setup.py test --coveralls

notifications:
  email: false
